
  # Stacks detected: deps:java:.
  version: 2.1
  jobs:
    test-java:

      docker:
        - image: cimg/openjdk:17.0
      steps:
        - checkout
        - restore_cache:
            key: cache-{{ checksum "pom.xml" }}
        - run:
            name: Run Tests with Maven
            command: mvn clean test
        - run:
            name: Run Tests with JaCoCo
            command: mvn clean verify
        - store_test_results:
            path: target/surefire-reports
        - run:
            name: Upload Coverage to Codecov
            command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
        - run:
            name: Run Checkstyle
            command: mvn checkstyle:check
        - store_artifacts:
            path: target/checkstyle-result.xml
            destination: checkstyle
        - run:
            name: Add SSH Key
            command: |
              mkdir -p ~/.ssh
              echo "$SSH_KEY" > ~/.ssh/id_rsa
              chmod 600 ~/.ssh/id_rsa
              ssh-keyscan github.com >> ~/.ssh/known_hosts

        - save_cache:
            key: cache-{{ checksum "pom.xml" }}
            paths:
              - ~/.m2/repository
    deploy:
      docker:
        - image: cimg/base:stable
      steps:
        - run:
            name: deploy
            command: '#e.g. ./deploy.sh'

    deploy-javadoc:
      docker:
        - image: cimg/openjdk:17.0
      steps:
        - checkout
        - run:
            name: Generate Javadoc
            command: mvn javadoc:javadoc
        - run:
            name: Deploy to GitHub Pages
            command: |
              git config --global user.email "ndeye.beye@etu.univ-amu.fr"
              git config --global user.name "Ndeye-Beye"
              git fetch origin gh-pages || true
              git checkout gh-pages || git checkout -b gh-pages
              mkdir -p docs
              cp -r target/site/apidocs/* docs/
              git commit -m "Deploy Javadoc"
              git push https://$TOKEN@github.com/Ndeye-Beye/ceri-m1-techniques-de-test.git gh-pages --force




  workflows:
    build-and-test:
      jobs:
        - test-java :
            filters:
              branches:
                only: master

        - deploy-javadoc:
           requires:
             - test-java
           filters:
             branches:
               only: master



