
  # Stacks detected: deps:java:.
  version: 2.1
  jobs:
    test-java:
      docker:
        - image: cimg/openjdk:17.0
      steps:
        - checkout
        - run:
            name: Run Tests with Maven
            command: mvn clean test
        - restore_cache:
            key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
        - run:
            name: Run Tests with JaCoCo
            command: mvn clean verify
        - store_test_results:
            path: target/surefire-reports
        - run:
            name: Upload Coverage to Codecov
            command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
        - run:
            name: Add SSH Key
            command: |
              mkdir -p ~/.ssh
              echo "$SSH_KEY" > ~/.ssh/id_rsa
              chmod 600 ~/.ssh/id_rsa
              ssh-keyscan github.com >> ~/.ssh/known_hosts

        - save_cache:
            key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
            paths:
              - ~/.m2/repository
    deploy:
      docker:
        - image: cimg/base:stable
      steps:
        - run:
            name: deploy
            command: '#e.g. ./deploy.sh'


  workflows:
    build-and-test:
      jobs:
        - test-java :
            filters:
              branches:
                only: master


