version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:23.jdk
    steps:
      - checkout

      - run:
          name: Install Maven
          command: sudo apt-get install -y maven

      - run:
          name: Run Tests
          command: mvn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master  # Déclenche seulement sur la branche master
