
  # Stacks detected: deps:java:.
  version: 2.1
  jobs:
    test-java:

      docker:
        - image: cimg/openjdk:17.0
      steps:
        - checkout
        - restore_cache:
            key: cache-{{ checksum "pom.xml" }}
        - run:
            name: Run Tests with Maven
            command: mvn clean test
        - run:
            name: Run Tests with JaCoCo
            command: mvn clean verify
        - store_test_results:
            path: target/surefire-reports
        - run:
            name: Upload Coverage to Codecov
            command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
        - run:
            name: Run Checkstyle
            command: mvn checkstyle:check
        - run:
            name: Add SSH Key
            command: |
              mkdir -p ~/.ssh
              echo "$SSH_KEY" > ~/.ssh/id_rsa
              chmod 600 ~/.ssh/id_rsa
              ssh-keyscan github.com >> ~/.ssh/known_hosts

        - save_cache:
            key: cache-{{ checksum "pom.xml" }}
            paths:
              - ~/.m2/repository
    deploy:
      docker:
        - image: cimg/base:stable
      steps:
        - run:
            name: deploy
            command: '#e.g. ./deploy.sh'

    deploy-javadoc:
      docker:
        - image: maven:3.8.7-openjdk-17
      steps:
        - checkout
        - run:
            name: Generate Javadoc
            command: mvn javadoc:javadoc
        - run:
            name: Deploy to GitHub Pages
            command: |
              git config user.name "CircleCI Bot"
              git config user.email "ndeye.beye@alumni.avignon.fr"
              git checkout --orphan gh-pages
              git rm -rf .
              mv target/site/apidocs/* .
              touch .nojekyll  # Avoid issues with files starting with underscores
              git add .
              git commit -m "Deploy Javadoc"
              git push origin gh-pages --force


  workflows:
    build-and-test:
      jobs:
        - test-java :
            filters:
              branches:
                only: master

        - deploy-javadoc:
           requires:
             - test-java
           filters:
             branches:
               only: master



